default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: shop_development
  username: <%= Rails.application.credentials.aws[:db_user] %>
  password: <%= Rails.application.credentials.aws[:db_password] %>
  encoding: unicode
  host: localhost
  pool: 5

test:
  <<: *default
  database: shop_test
  username: <%= Rails.application.credentials.aws[:db_user] %>
  password: <%= Rails.application.credentials.aws[:db_password] %>
  encoding: unicode
  host: localhost
  pool: 5

production:
  adapter: postgresql
  host: 127.0.0.1
  database: shop
  username: deployer
  password: denuk96
  encoding: unicode
  pool: 5
#  <<: *default
#  database: shop_production
#  username: <%#= Rails.application.credentials.aws[:db_user] %>
#  password: <%#= Rails.application.credentials.aws[:db_password] %>
